### ISSUE TITLE
Server dominator/arbitration is not being maintained

### ISSUE THREAD

**Issue by gary-menzel** [msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks#36]
I've implemented V3.0.1 (with the 'failed/failure' fix) but that is not my issue (nothing is failing right now)....

The server arbitration (dominator) does not appear to be working properly.

Here is a screenshot of my dominator table (3 instances running).....

![image](https://user-images.githubusercontent.com/5697099/36974821-2c4207e0-20cc-11e8-9b34-1d0f6c4652de.png)

Here is a screenshot of my `getEmails` job running (out of control)....

![image](https://user-images.githubusercontent.com/5697099/36974850-42a80a34-20cc-11e8-88a2-d65e504eafdb.png)

It always creates 3 copies of the `getEmails` job and sets them as pending - and then it only seems to resolve one of them and then goes on to create 3 more pending jobs.

**Comment by gary-menzel** [comment]
NOTE: the server id is using the new "user supplied" functionality - the first section is the application ID the second is the server ID and the third is the deployed version number.

**Comment by msavin** [comment]
Can you please post the job registration and how you are calling them?

**Comment by gary-menzel** [comment]
I am happy to do so but It is fairly complex - I am modelling it off the MeteorPromise code that was shared in the other issue (mainly because that mechanism uses asynchronous imap calls).  However, it all runs fine on a single instance.

**Comment by gary-menzel** [comment]
I'll post it in pieces..... 

Here is the startup code that is called once when an instance starts:

```javascript
  const repeatInterval = { in: { minutes: 0, seconds: 15 } }; // we might eventually get this as a setting
  const normalTest = true;
  if (Meteor.settings.environment !== 'development' || normalTest) {
    repeatInterval.in.minutes = 5; // 5 minutes
    repeatInterval.in.seconds = 0;
  }

  registerJob({ name: 'getEmails', job: getEmails, wrap: true, runConfig: repeatInterval });
  
  const getEmailJob = JobsInternal.Utilities.collection.findOne({ name: 'getEmails', state: 'pending' });
  if (getEmailJob) {
    const { repeatInterval: runConfig } = getEmailJob.arguments[0];
    console.log(`getEmails job already running... every ${runConfig.in.minutes}m ${runConfig.in.seconds}s - _id: ${getEmailJob._id}`);
  } else {
    const { cyl } = Meteor.settings.external_email;
    const { credentials } = cyl;
    credentials.accountId = RMX.settings.emailCollect.cylAccount;
    const cylQuery = getQuery(cyl.credentials); // , true);
    const params = { query: cylQuery, repeatInterval };
    
    Jobs.run('getEmails', params);
    
    console.log(`getEmails job registered... every ${repeatInterval.in.minutes}m ${repeatInterval.in.seconds}s on server ID: ${JobsInternal.Utilities.config.getServerId()}`);
  }
```
The `registerJob` is what I will post next as it has the MeteorPromise stuff in it.

**Comment by gary-menzel** [comment]
`registerJob` provides a consistent way to wrap a "normal" function in a MeteorPromise and it manages ensuring the outcome calls are sent back to the Jobs package:

```javascript
export const JobResult = {
  SUCCESS: 'SUCCESS',
  RETRY_WITH_DELAY: 'RETRY_WITH_DELAY',
  FAILURE: 'FAILURE',
};

export function jobWrapper(name, job, runConfig) {
  // console.log('jobWrapper:', { name, job, runConfig });
  return async (instance, args) => {
    // console.log('jobWrapper run:', { instance, args });
    try {
      const result = await job(args, instance);
      // console.info(`Result (${name}): ${result}`);
      switch (result) {
        case JobResult.SUCCESS:
          if (runConfig) {
            console.info(`Replicating (${name}) job to run in approximately ${runConfig.in.minutes}m ${runConfig.in.seconds}s`);
            instance.replicate(runConfig);
          }
          instance.success();
          break;
        case JobResult.RETRY_WITH_DELAY:
          console.info(`Retrying (${name}) due to result.`);
          instance.reschedule(runConfig || { in: { minutes: 5 } });
          break;
        case JobResult.FAILURE:
          console.info(`Failure of (${name}) due to random failure.`);
          instance.failure('random failure');
          break;
        default:
          console.error(`Unknown job result. ${result}`);
          // if (runConfig) instance.reschedule(runConfig);
          break;
      }
    } catch (error) {
      const message = `jobWrapper: Error executing job ${name}: ${error.message}. ${runConfig ? 'Retrying' : 'Stopping'}.`;
      console.log(message);
      if (runConfig) {
        instance.reschedule(runConfig);
      }
    }
  };
}

export function registerJob({ name, job, wrap, runConfig }) {
  // console.info(`Registering ${name} job.`);
  const run = wrap ? jobWrapper(name, job, runConfig) : job;
  Jobs.register({
    [name](args) {
      MeteorPromise.await(run.apply(this, [this, args]));
    },
  });
}
```

**Comment by gary-menzel** [comment]
So, in short:
- the `registerJob` function doesn't do much except take care of wrapping the function (if it also uses Promises) and then calls `register` on the jobs package
- I check to see if the Job already exists in the database as `pending` and just report it if it is
- If it does not exist, then it says to run the job - and reports it has done so

**Comment by gary-menzel** [comment]
Also, just let me clarify what my understanding is of how it should work:
- The instance with the dominator record with the most recent `lastPing` will run the job
- The other two will look at the job but, because they don't have the most recent `lastPing` then they will just do a NOOP
- The server that "won" will run the job and, if it needs to be replicated/rescheduled, will do so

I can see how I might be creating 3 records - because each server might think that they should create the record (if it does not exist) - but I don't know how to "fix" that (if that is what is causing the problem) because none of the instances knows about the other.

**Comment by gary-menzel** [comment]
I've just realised (also) that while this particular problem is with a repeating job, I also have a 'sendEmail' job that all 3 instance are looking out for (and that would explain why some bulk emails that went out last Friday were sent up to 3 times).

**Comment by gary-menzel** [comment]
FYI - I'll check back in about 6 hours time (0032hrs here)

**Comment by gary-menzel** [comment]
I had a think about how the dominator works and I think it needs to write the "active" dominator ID out to the job_data record if it is `run` by the inactive instances (rather than its own ID) but copied when it is replicated (which should be the "active" instance anyway).  Then, the job is read back by all of them and only executed if that instance ID is in the job OR if the timeout has passed that indicates the original "active" has become non-responsive.  At the moment, it looks like each writes out it's own record - creating three of them.  This should only be done for jobs that have a schedule. [there may be other things to consider as well]

I've put in a block on a restart so that the repeating job won't be run by any of my instances for now (I have to set a DB flag and restart an instance to get it to hit `run`).

I realise that we are both busy and understand if this is a bigger problem to solve than first thought.  I have never built a Meteor package (I write all my own modules locally) but it seems like I could just lift your `import` directory and drop it straight into my project and test out my idea.  I have a "day" job and will be going to that soon and won't be looking at this for about 12 hours.  If I go down that path and get a resolution, I'll keep this issue up-to-date of any developments.

**Comment by msavin** [comment]
Regarding Dominator - I had a dumb MongoDB error, instead of sorting with `-1`, I used `1` and so it would pull the oldest document instead of the newest, and then say "hey, I guess I should do this." 

It's likely that this is why it was enough to get the job to run three times on the server, assuming there are three servers. Each job ran and replicated itself as expected. 

Thanks for bearing with these bugs! I hope that's the last of it. I pushed the latest package version to Atmosphere (3.0.2). Please let me know how it's working for you.

Regarding running packages locally - you just have to copy and paste the package folder into `./mymeteorapp/packages/packageName` and make sure that package.js and its relative files are in the packageName folder. Then your run `meteor add packageName` and it will be there. It's quite handy if you want to group client and server functionality into one unit.

**Comment by gary-menzel** [comment]
(WHOOPS - forget this - I was so excited I missed the bit about the `.mymeteorapp...`)

I also have an idea of running up two instances of my app locally - on different ports.  They won't be running behind a load balance or as replaceable instances but I can probably then simulate a multi-server environment.

**Comment by msavin** [comment]
@gary-menzel that would be great. It's actually very easy to make and run packages. What I am doing is basically copying the `./package` folder from this repo into `app/packages/package` and then I run `meteor add msavin:sjobs`. 

The only issue you might have there is, if the package version number is behind, or the same, as the one on Atmosphere, Meteor might run its cached one rather than your local one. You can get around it 
by incrementing the local package version.

Regarding running multiple instances locally - if you need to simulate this, you can set up one MongoDB instance and then run multiple local servers on different ports, and have them connect to the remote database.

**Comment by gary-menzel** [comment]
I have updated to 3.0.2 and am running two instances (I run a stand alone Mongo even for development) but, sadly, two jobs are still getting created.....

So, as to not waste any more of your time (at least for now), I will copy the package in locally and start tracing through to solve it.  I'll report back here - either success or fail.

Thanks for all your help so far - hopefully I can contribute back some useful updates.

**Comment by gary-menzel** [comment]
Thinking about this....
- Each instance HAS to have a call to `run` because at least one job record needs to go into the DB. The problem comes when each server instance thinks IT has the job.
- Maybe we could add a flag in the `config` passed when a job is `run` that is called `unique` and do an extra check before and after to make sure that the job record is only created once ?
- Maybe we could also check to see that the `serverId` in the `unique` job record is the same as the current dominating instance ?
- Then we might avoid the initial 3 (or more) jobs getting created and could make sure that only the dominator runs unless it stops responding (as per the original specifications)

[PS: I do have the package installed my local packages folder now - so I can start to experiment with this.]

**Comment by ramijarrar** [comment]
@gary-menzel Just getting caught up with the discussion here. We ran into a similar issue for repeat jobs and wrote some logic to ensure only one instance runs per interval:

```js
import { Promise } from 'meteor/promise';
import { Jobs, JobsInternal } from 'meteor/msavin:sjobs';

export function registerRepeatJob({ name, run, config, retryMinutes }) {
  Jobs.register({
    [name](...parameters) {
      const jobContext = this;

      // Add specified repetition cycle (overriding any previous schedules)
      const existingCycles = JobsInternal.Utilities.collection.find({
        name,
        _id: { $ne: jobContext.doc._id },
        state: 'pending',
      }).fetch();
      if (existingCycles.length > 0) {
        existingCycles.forEach(instance => Jobs.cancel(instance._id));
      }
      jobContext.reschedule(config);

      // Log cycle details
      console.log(`Job cycle run: ${name} [${JSON.stringify(config)}]`);

      // Wrap job execution
      try {
        /* Forward context/params to 'run' method - execute in a top-level fiber-aware await to
         allow regular async-await syntax in provided function */
        Promise.await(run.apply(jobContext, parameters));
      } catch (error) {
        // Log error message
        console.log(`Job cycle error: ${error.message}`);

        // Throttle retry after failure to avoid overloading the server
        jobContext.reschedule({ in: { minutes: retryMinutes } });
      }
    },
  });
}
```

Only catch with this is that it overrides the cycle on a restart/deploy (which is the intended behavior for us, but you could preserve this by cancelling the current instance rather than previous).

**Comment by gary-menzel** [comment]
@ramijarrar - thanks...
I am looking at doing something similar but the problem I am having at the moment is that the other instances may run before they are killed so more job records get created.  What I want is for only ONE job record to be created for this specific task (that gets emails from an imap server) and only have ONE server run that.

Essentially, I am looking at doing your "existingCycles" when a job is `run` and then NOT creating one if there is already one there (rather than trying to get the dominator to kill any additional ones).  I suppose it is the same outcome - however, I am still convincing myself that only the dominator runs.  If I build in this "unique" protection when the job is first run then it won't matter about who runs it.

The main difference between `reschedule` and `replicate` is that `reschedule` reuses the same job - which is maybe what I really want anyway - but the history can then bloat out.  But then, using `replicate`, the database records can bloat out as well.

I'll probably look at only keeping a certain range (maybe 48 hours) of job history anyway.

**Comment by gary-menzel** [comment]
So here is my update as of 2145 AEST 2018-03-07....

I did load the package locally - it did make it easier to debug as I could easily drop on trace statements.  However, in the end, the only thing that I modified was the `Meteor.isDevelopment` check as I needed to run two instances (as though it was in Production) and did not want to set the Production flag.  Maybe this could be converted to an `isDevelopment` or `isSingle` function in the config (like the `getServerId`)......

In any case, what I did was wrapped the `Jobs.run`method and called it `runJob` (I had already wrapped the `Jobs.register` as `registerJob`).  The wrapper reads the DB first to see if the job already exists (yes - I might have to also check that it is a repeating job but "immediate" jobs get handled fairly quickly and are usually only generated once - e.g. a bulk outgoing email generates a job for each email to be sent and that would all come from one server).

So...
- If the job already exists, then it just performs a NOOP and returns the actual job it found.
- If the job DOESN'T exist it does two things:
  - Calls `Jobs.run`
  - Reads all the jobs of that name that are pending back again and, if there is more than one now (because maybe another server jumped in during the gap), it fully deletes the job it just created (using `JobsInternal.Utilities.collection.remove(job._id)` ).

During my local testing, the imap service that is backing my `getEmails` job actually had a timeout error.  The job failed as expected.  When I restarted the server, the Failed job was retried (but did get an error due to the arguments not being there for some reason I have not worked out yet) BUT - it all recovered anyway as the repeating job still got written back out and things moved one without further issue.

I have now separately killed each of the running instances a couple of times and watched the other instance pick up the jobs and run them.  When I bring the other online it sits idle until the other is killed.

Finally......

At this point in time I don't think I have anything to contribute back to the package as I built all of my fixes outside (bar the `isDevelopment` flag).  However, I plan to leave the package local rather than tied to the Atmosphere service as I want to be able to debug further if anything else happens.  That means I am "disconnected" from the main branch for now.

[I've got so much to do but will probably get back to this eventually and see if I can enhance anything.  Some of my functions could probably be incorporated as additional features - like `registerWithPromise` and `runUnique` - or something like that.]

**Comment by msavin** [comment]
@gary-menzel I haven't had a chance to read all of this yet - but just to confirm - are you running any of your apps in development mode?

Especially the production ones.. if so, that would be why you are having this problem.

**Comment by gary-menzel** [comment]
@msavin Yes, seasoned Meteor developer here - I am aware of the difference between development and production modes.

I even have different settings json files for each environment and am fully across all of that.  It is not related to that.

It is just that I find running in production mode locally hampers debugging so I don't use the production flag.  So I wanted to run in development mode and be able to run two instances of the app at the same time.  It was only the `isDevelopment` check that stopped that.

I did get everything working perfectly without changing your code and just ensuring that there was only a unique instance of the job in the DB.  That included stopping/starting the instances and having the failover working.

However, I did something (too late in my day when I should have been asleep) and I broke it again.

So, for now, put the "good news" on old while I deal with my day job.

**Comment by msavin** [comment]
For what its worth, I ran some quick tests and was not able to reproduce:

1. Ran `JobsInternal.Operator.dominator.isActive()`, and received a truthy value
2. Ran `JobsInternal.Operator.dominator.reset()`, which changed the serverId.
3. `JobsInternal.Operator.dominator.isActive()` began to return `false`. This is working as expected, because the previous serverId's ping time was still with-in the "grace" time period.
4. Scheduled a job with `Jobs.run` - job was scheduled but did not run
5. Ran `JobsInternal.Operator.dominator.setAsActive` to force the current serverId as the current one, and job ran successfully 

I will look into this some more tomorrow

**Comment by msavin** [comment]
This looks to be the bug:

https://github.com/msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks/commit/

This is what I get for dropping out of high school...

Published to Atmosphere as 3.0..4

**Comment by msavin** [comment]
This looks to be the bug:

https://github.com/msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks/commit/7f10a0bfe41d05f6be513bf3b3830915ea6c6f70

This looks like what I get for dropping out of high school.

Published to Atmosphere as 3.0.4

**Comment by gary-menzel** [comment]
I will check tonight.  My other solution is "working" now - so I am going to be careful not to break it (but this should be easy to test).

**Comment by msavin** [comment]
Long story short, unless by some bizarre odds I fixed the bug during a refactor, I am unable to reproduce this problem.

Here's what I did: 
1. Added support for `remoteCollection` into the Jobs package (it is not published, but is in repo)
2. Started two Meteor servers, which connect to the same database
3. Registered the same job on both servers
4. Added support for `disableDevelopmentMode` and enabled it
5. Ran a recurring job on one server

The job ran on the right server. I hacked around with `dominator`, in some cases forcing one server to take dominance, and everything worked as expected.

On one server, I configured:

``javascript
Jobs.configure({
	remoteCollection: "mongodb://127.0.0.1:3001/meteor",
	disableDevelopmentMode: true
})

Jobs.register({
	"sayHi": function (name) {
		console.log("Hi " + name);
		this.replicate({
			in: {
				seconds: 2
			}
		})
		this.success()
	}
})
```

and on the second server, I set:

```
Jobs.configure({
	disableDevelopmentMode: true
})

Jobs.register({
	"sayHi": function (name) {
		console.log("Hi " + name);
		this.replicate({
			in: {
				seconds: 2
			}
		})
		this.success()
	}
})
```

@gary-menzel can you try another job - maybe something like a doc insert - just to rule out that its not something with the job you've written?

**Comment by gary-menzel** [comment]
I already did that and I was happy with the results (although, on discussion with the client, the repeating job is not as important as the outgoing emails, so it is currently disabled in PRODUCTION).  However, I still think the comparison sign in the `dominator` should be `>=` (not `<=`) as per my comment in

https://github.com/msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks/commit/7f10a0bfe41d05f6be513bf3b3830915ea6c6f70

You only want to take over if the gap is greater than the maximum.  The `master` branch still has the sign the other way.  I am not sure if you are running locally with the comparison the right way but that is how I have it and when I actually completely kill a running instance the other takes over perfectly.

With your Point 3 - did you create two job records or does your code avoid that ?  That was core to my problem because if you create two (or more) then the single `dominator` will run eventually run all of them.  If servers are then restarted by a service provider, more jobs get created, etc.

So the "kickstart" process is important. I now do something like this.....
```javascript
  Jobs.register({
    handleJob,
  });
  
  const job = JobsInternal.Utilities.collection.findOne({ name: 'handleObj', state: 'pending' });
  if (!job) {
    const repeatInterval = { in: { minutes: 5, seconds: 0 } }; 
    const args = {
      avalue: 1,
      astring: 'A String',
      adate: new Date(),
      repeatInterval,
    };
    
    console.log('repeating job "handleJob" not found - starting:', { serverId: JobsInternal.Utilities.config.getServerId() });
    Jobs.run('handleJob', args, repeatInterval);
  } else {
    console.log('"handleJob" already running:', { serverId: job.serverId });
  }
```

As I said, I am still running a copy of the package locally.  I will try with the Atmosphere package again eventually but need to be able to hack something in quickly for now.

**Comment by msavin** [comment]
Regarding `dominator` - yes the change was rolled back

----

Do you mean that you had the job being created on each server startup?

For example:

```
Jobs.run("work", {
  in: { minutes: 5 }
})
```

Then yes - this will create the job on each server startups, which would explain the problem.

Here's how you would "kickstart" a function:

```
Meteor.startup(function ( ) { 
  if (!JobsInternal.Utilities.collection.findOne({ name: 'handleObj', state: 'pending' })) {
    Jobs.run("work", {
      in: { minutes: 5 }
    })
 }
})

**Comment by gary-menzel** [comment]
Yes - that was part of the issue.  It was not clear from the docs about that (I had thought the dominator would take care of it but then realised it doesn't).

However, the switching the comparison sign was also a contributor as it caused more than one instance to think it should be running.

I think I am all OK with this issue now.

So we can close it off - I just have to get back to repeating jobs again in the not too distant future and then I can delve into this again.

**Comment by msavin** [comment]
@gary-menzel cool - thanks for letting me know. Most likely, I will add something like `Jobs.runIfNoJobsPending` to circumvent this issue - as it came up a number of times.
